/* This is auto-generated code from LDmicro. Do not edit this file! Go
   back to the ladder diagram source for changes in the logic, and make
   any C additions either in ladder.h or in additional .c files linked
   against this one. */

/* You must provide ladder.h; there you must provide:
      * a typedef for SWORD and BOOL, signed 16 bit and boolean types
        (probably typedef signed short SWORD; typedef unsigned char BOOL;)

   You must also provide implementations of all the I/O read/write
   either as inlines in the header file or in another source file. (The
   I/O functions are all declared extern.)

   See the generated source code (below) for function names. */
#include "ladder.h"

/* Define EXTERN_EVERYTHING in ladder.h if you want all symbols extern.
   This could be useful to implement `magic variables,' so that for
   example when you write to the ladder variable duty_cycle, your PLC
   runtime can look at the C variable U_duty_cycle and use that to set
   the PWM duty cycle on the micro. That way you can add support for
   peripherals that LDmicro doesn't know about. */
#ifdef EXTERN_EVERYTHING
#define STATIC 
#else
#define STATIC static
#endif

/* Define NO_PROTOTYPES if you don't want LDmicro to provide prototypes for
   all the I/O functions (Read_U_xxx, Write_U_xxx) that you must provide.
   If you define this then you must provide your own prototypes for these
   functions in ladder.h, or provide definitions (e.g. as inlines or macros)
   for them in ladder.h. */
#ifdef NO_PROTOTYPES
#define PROTO(x)
#else
#define PROTO(x) x
#endif

/* Below is the definition of the internal buffers for I/O and memory.
   They are mapped externally and can be accessed by Modbus. */
SWORD AnalogInputBuffer0[100];
SWORD AnalogOutputBuffer0[100];
BOOL DiscreteInputBuffer0[100];
BOOL CoilsBuffer0[100];

SWORD MemBuffer0[100];
SWORD MemBuffer1[100];
SWORD MemBuffer2[100];

/* U_xxx symbols correspond to user-defined names. There is such a symbol
   for every internal relay, variable, timer, and so on in the ladder
   program. I_xxx symbols are internally generated. */
STATIC BOOL I_b_mcr = 0;
STATIC BOOL I_b_rung_top = 0;
STATIC BOOL *U_b_X0_0 = &DiscreteInputBuffer0[0];
STATIC SWORD *U_i_M0_0 = &MemBuffer0[0];
STATIC BOOL *U_b_X0_1 = &DiscreteInputBuffer0[1];
STATIC BOOL I_b_scratch = 0;
STATIC BOOL I_b_oneShot_0000 = 0;
STATIC SWORD I_i_scratch2 = 0;
STATIC BOOL *U_b_Y0_0 = &CoilsBuffer0[0];
STATIC SWORD *U_i_M0_1 = &MemBuffer0[1];
STATIC SWORD *U_i_I0_0 = &AnalogInputBuffer0[0];
STATIC SWORD *U_i_M0_2 = &MemBuffer0[2];
STATIC SWORD *U_i_I0_1 = &AnalogInputBuffer0[1];
STATIC BOOL *U_b_X0_4 = &DiscreteInputBuffer0[4];
STATIC BOOL I_b_oneShot_0001 = 0;
STATIC BOOL I_b_T1_antiglitch = 0;
STATIC SWORD U_i_T1 = 0;
STATIC BOOL *U_b_Y0_2 = &CoilsBuffer0[2];


/* Call this function once per PLC cycle. You are responsible for calling
   it at the interval that you specified in the MCU configuration when you
   generated this code. */
void PlcCycle(void)
{
    I_b_mcr = 1;
    
    /* start rung 1 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    if(*U_b_X0_0) {
        I_b_rung_top = 0;
    }
    
    if(I_b_rung_top) {
        *U_i_M0_0 = 1;
    }
    
    /* ] finish series */
    
    /* start rung 2 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    if(*U_b_X0_1) {
        I_b_rung_top = 0;
    }
    
    I_b_scratch = I_b_rung_top;
    if(I_b_oneShot_0000) {
        I_b_rung_top = 0;
    }
    I_b_oneShot_0000 = I_b_scratch;
    
    if(I_b_rung_top) {
        I_i_scratch2 = 1;
        *U_i_M0_0 = *U_i_M0_0 + I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 3 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    I_i_scratch2 = 5;
    if(I_i_scratch2 > *U_i_M0_0) {
        I_b_rung_top = 0;
    }
    
    *U_b_Y0_0 = I_b_rung_top;
    
    /* ] finish series */
    
    /* start rung 4 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    if(I_b_rung_top) {
        *U_i_M0_1 = *U_i_I0_0;
    }
    
    /* ] finish series */
    
    /* start rung 5 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    if(I_b_rung_top) {
        *U_i_M0_2 = *U_i_I0_1;
    }
    
    /* ] finish series */
    
    /* start rung 6 */
    I_b_rung_top = I_b_mcr;
    
    /* start series [ */
    if(*U_b_X0_4) {
        I_b_rung_top = 0;
    }
    
    I_b_scratch = I_b_rung_top;
    if(I_b_oneShot_0001) {
        I_b_rung_top = 0;
    }
    I_b_oneShot_0001 = I_b_scratch;
    
    if(!I_b_T1_antiglitch) {
        U_i_T1 = 39;
    }
    I_b_T1_antiglitch = 1;
    if(!I_b_rung_top) {
        if(U_i_T1 < 39) {
            U_i_T1++;
            I_b_rung_top = 1;
        }
    } else {
        U_i_T1 = 0;
    }
    
    *U_b_Y0_2 = I_b_rung_top;
    
    /* ] finish series */
}
